{
 "title": "Churn dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Shares of count missing values",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}