name: CI-tests
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.55.0
          cache: true
      - name: Install dependencies and run tests
        run: |
          pixi install && \
          pixi add python=3.12 && \
          pixi run pytest --ignore=tests/api/test_main.py --ignore=tests/bank_customer_churn_prediction_pipeline/test_flow_tasks.py
